(()=>{'use strict';
const $=id=>document.getElementById(id),c=$('court'),ctx=c.getContext('2d'),g=new Tennis(5829);let W=0,H=0,S=0,dpr=1,bg=document.createElement('canvas'),bc=bg.getContext('2d'),last=0,acc=0,clock=0,particles=[],flash=0,toastUntil=0,soundOn=false,audio=null,keys={},aim=0,stickId=null,hitId=null,hitStartX=0;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function project(x,y,z=0){let q=.67+(y+12)/24*.65;return {x:W*.5+x*S*q,y:H*.32+(y+12)*H*.0209-z*S*q*.92,s:S*q};}
function path(points,fill,stroke,width=1){ctx.beginPath();points.forEach((v,i)=>{let p=project(...v);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});if(fill){ctx.closePath();ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function line(a,b,col,width=1){path([a,b],null,col,width)}
function ellipse(x,y,rx,ry,color,alpha=1){ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
function buildBackground(){bg.width=Math.round(W*dpr);bg.height=Math.round(H*dpr);bc.setTransform(dpr,0,0,dpr,0,0);let x=bc;let sky=x.createLinearGradient(0,0,0,H*.38);sky.addColorStop(0,'#9bbec0');sky.addColorStop(.52,'#dde0c3');sky.addColorStop(1,'#f4d4a3');x.fillStyle=sky;x.fillRect(0,0,W,H);let seed=894;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 // Distant wooded ridge and a softly lit evening sky.
 for(let layer=0;layer<3;layer++){x.beginPath();x.moveTo(0,H*.28);for(let i=0;i<=W+40;i+=40)x.lineTo(i,H*(.14+layer*.025)-Math.sin(i*.005+layer)*H*.035-rand()*H*.025);x.lineTo(W,H*.32);x.closePath();x.fillStyle=['#849d8c','#6c8e77','#496e5b'][layer];x.fill();}
 x.fillStyle='#113e32';x.fillRect(0,H*.19,W,H*.17);x.fillStyle='#244d3c';x.fillRect(0,H*.155,W,H*.025);
 // Tiered stands. Fans use small heads, clothing and seats rather than rectangles.
 for(let r=0;r<6;r++){let yy=H*(.17+r*.019);x.fillStyle=r%2?'#747a59':'#8f9270';x.fillRect(0,yy,W,H*.017);x.fillStyle='#354f3b';x.fillRect(0,yy+H*.014,W,H*.006);for(let xx=-10;xx<W+15;xx+=14){if(rand()<.12)continue;let px=xx+rand()*4,py=yy+H*.011;let body=['#e7d5a6','#eee7cd','#a6b7a8','#b97655','#c7c6ac','#406659'][Math.floor(rand()*6)];x.fillStyle=body;x.beginPath();x.ellipse(px,py,3.3,5.4,0,0,Math.PI*2);x.fill();x.fillStyle=rand()>.5?'#c88e67':'#e5b587';x.beginPath();x.arc(px,py-5.4,2.3,0,Math.PI*2);x.fill();x.fillStyle='#3c4633';x.fillRect(px-2.4,py-8,4.8,1.3);}}
 for(let xx=-W;xx<W*2;xx+=W*.27){x.fillStyle='#b7b393';x.beginPath();x.moveTo(xx,H*.17);x.lineTo(xx+13,H*.17);x.lineTo(xx+36,H*.29);x.lineTo(xx+18,H*.29);x.fill();}
 x.fillStyle='#163f31';x.fillRect(0,H*.286,W,H*.047);x.fillStyle='#dce4b44d';x.fillRect(0,H*.289,W,1);x.textAlign='center';x.font=`600 ${Math.max(9,S*.38)}px Georgia`;x.fillStyle='#ced7ac';for(let i=0;i<5;i++)x.fillText(i%2?'SUNSET OPEN':'CLAY CLUB',W*(i+.5)/5,H*.317);x.fillStyle='#e6d4a3';x.fillRect(0,H*.332,W,2);
 let ground=x.createLinearGradient(0,H*.33,0,H);ground.addColorStop(0,'#bd7050');ground.addColorStop(.5,'#ce8059');ground.addColorStop(1,'#c4845e');x.fillStyle=ground;x.fillRect(0,H*.335,W,H);for(let i=0;i<18000;i++){let xx=rand()*W,yy=H*.335+rand()*H*.665;x.fillStyle=rand()>.5?'#fbd3a313':'#7d422715';x.fillRect(xx,yy,rand()*1.9+.2,.6);}
 // Sunlight across the clay.
 let sunlight=x.createRadialGradient(W*.74,H*.49,0,W*.74,H*.49,W*.85);sunlight.addColorStop(0,'#ffdda124');sunlight.addColorStop(1,'#773f3917');x.fillStyle=sunlight;x.fillRect(0,H*.33,W,H*.67);
}
function resize(){W=window.innerWidth;H=window.innerHeight;dpr=Math.min(window.devicePixelRatio||1,2);S=Math.min(W/14.6,H/19);c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);buildBackground();}window.addEventListener('resize',resize);resize();
function drawCourt(){path([[-5.485,-11.885],[5.485,-11.885],[5.485,11.885],[-5.485,11.885]],'#b9684530','#f9efd3',2);for(let x of [-4.115,4.115])line([x,-11.885],[x,11.885],'#fff4dbe8',2);line([-4.115,-6.4],[4.115,-6.4],'#f8e9cf',1.7);line([-4.115,6.4],[4.115,6.4],'#fff0d9',2);line([0,-6.4],[0,6.4],'#fbedce',1.8);line([0,-11.885],[0,-11.5],'#fff2d6',2);line([0,11.885],[0,11.5],'#fff2d6',2);
 // Short drag marks and baseline wear are deliberately subtle.
 for(let j=0;j<4;j++)path([[-3+j*.55,10.1+j*.2],[-2.7+j*.55,10.4+j*.2],[-2.1+j*.55,10.55+j*.2]],null,'#ecc09233',1);
 path([[-5.8,-.06],[5.8,-.06],[6.6,1.15],[-5.3,1.15]],'#433d2530');
}
function drawNet(){for(let y=0;y<=.9;y+=.115)line([-5.65,0,y],[5.65,0,y],'#f7e8cb65',.65);for(let x=-5.65;x<=5.7;x+=.17)line([x,0,.04],[x,0,.92-Math.max(0,1-Math.abs(x)/5.65)*.07],'#fff0cd70',.65);line([-5.65,0,.97],[0,0,.88],'#fff4d8',3);line([0,0,.88],[5.65,0,.97],'#fff4d8',3);for(let x of [-5.7,5.7]){line([x,0,0],[x,0,1.12],'#1b493b',5);let p=project(x,0,1.15);ellipse(p.x,p.y,3,2,'#d0d1a3');}}
function drawPlayer(p,who){let ground=project(p.x,p.y),unit=ground.s,swing=p.swing,phase=p.run,bob=p.moving?Math.sin(phase*2)*.03:Math.sin(clock*2)*.01;let P=(x,z)=>({x:ground.x+x*unit,y:ground.y-(z+bob)*unit*.92});ellipse(ground.x+unit*.3,ground.y+unit*.03,unit*.55,unit*.13,'#583f2c',.26);let lean=p.moving?Math.sin(phase)*.08:0,hip=P(lean,.92),neck=P(lean+.025,1.48),head=P(lean+.025,1.7);let stride=p.moving?Math.sin(phase)*.28:.12;
 function seg(a,b,col,w){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineWidth=w*unit;ctx.strokeStyle=col;ctx.lineCap='round';ctx.stroke();}
 const skin=who===0?'#c88e61':'#dca071',shirt=who===0?'#f1e7cf':'#476f83',dark=who===0?'#213e36':'#213645';let lk=P(-.16+stride,.49),rk=P(.17-stride,.48),lf=P(-.19+stride*.7,.08),rf=P(.21-stride*.7,.08);
 seg(P(-.12,.84),lk,dark,.2);seg(P(.13,.84),rk,dark,.2);seg(lk,lf,skin,.105);seg(rk,rf,skin,.105);seg({x:lf.x,y:lf.y-unit*.13},lf,'#f1e3c3',.11);seg({x:rf.x,y:rf.y-unit*.13},rf,'#f1e3c3',.11);seg(lf,{x:lf.x+unit*.14,y:lf.y+unit*.012},'#fcf1d4',.13);seg(rf,{x:rf.x+unit*.14,y:rf.y+unit*.012},'#fcf1d4',.13);
 ctx.beginPath();let a=P(-.24+lean,1.47),b=P(.22+lean,1.47),c=P(.18+lean,.93),d=P(-.17+lean,.93);ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(neck.x,neck.y-unit*.09,b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.closePath();let grad=ctx.createLinearGradient(a.x,0,b.x,0);grad.addColorStop(0,who===0?'#cabfa5':'#315666');grad.addColorStop(.45,shirt);grad.addColorStop(1,who===0?'#fff2d7':'#65889a');ctx.fillStyle=grad;ctx.fill();seg(P(-.18+lean,1.4),P(.15+lean,1.4),who===0?'#4d6b52':'#e2dec6',.035);seg(P(-.13+lean,.91),P(.14+lean,.91),dark,.18);
 let theta=swing>0?(-1.8+swing*4.7):.5,elbow=P(.38+lean,1.12),hand=P(.5+Math.cos(theta)*.28,1.05+Math.sin(theta)*.37),leftElbow=P(-.34+lean,1.14),leftHand=P(-.2+lean,1.02);
 seg(a,leftElbow,skin,.115);seg(leftElbow,leftHand,skin,.09);seg(b,elbow,skin,.115);seg(elbow,hand,skin,.09);seg(P(lean+.025,1.45),P(lean+.025,1.6),skin,.13);ellipse(head.x,head.y,unit*.13,unit*.17,skin);ellipse(head.x,head.y-unit*.09,unit*.145,unit*.095,who===0?'#26342a':'#493b2e');if(who===0){ctx.fillStyle='#22392f';ctx.beginPath();ctx.ellipse(head.x,head.y-unit*.03,unit*.13,unit*.115,0,Math.PI,Math.PI*2);ctx.fill();}else{seg({x:head.x-unit*.13,y:head.y-unit*.03},{x:head.x+unit*.17,y:head.y-unit*.03},'#e6e3ce',.055);}
 let ra=theta-.5,rx=hand.x+Math.cos(ra)*unit*.42,ry=hand.y-Math.sin(ra)*unit*.42;seg(hand,{x:rx,y:ry},'#243c38',.045);ctx.save();ctx.translate(rx+Math.cos(ra)*unit*.2,ry-Math.sin(ra)*unit*.2);ctx.rotate(-ra);ctx.strokeStyle=who===0?'#e8eabc':'#edab77';ctx.lineWidth=unit*.035;ctx.beginPath();ctx.ellipse(0,0,unit*.28,unit*.18,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(0,0,unit*.245,unit*.15,0,0,Math.PI*2);ctx.clip();ctx.strokeStyle='#eeeddba0';ctx.lineWidth=.5;for(let q=-.2;q<.25;q+=.065){ctx.beginPath();ctx.moveTo(q*unit,-unit*.2);ctx.lineTo(q*unit,unit*.2);ctx.moveTo(-unit*.3,q*unit);ctx.lineTo(unit*.3,q*unit);ctx.stroke();}ctx.restore();ctx.lineCap='butt';}
function drawBall(){let b=g.ball,p=project(b.x,b.y,b.z),shadow=project(b.x+b.z*.25,b.y+b.z*.1);ellipse(shadow.x,shadow.y,p.s*(.11+b.z*.025),p.s*.045,'#384526',.32/(1+b.z*.25));if(b.active){g.trail.forEach((a,i)=>{let t=project(a.x,a.y,a.z);ellipse(t.x,t.y,Math.max(1,t.s*.058),Math.max(1,t.s*.058),'#fbffd1',i/g.trail.length*.24);});}let r=Math.max(3.6,p.s*.09);ctx.save();ctx.shadowColor='#f4fb98';ctx.shadowBlur=7;ellipse(p.x,p.y,r,r,'#edf28b');ctx.restore();ctx.strokeStyle='#ffffe5';ctx.lineWidth=Math.max(.7,r*.23);ctx.beginPath();ctx.arc(p.x-r*.52,p.y,r*.74,-1.2,1.2);ctx.stroke();}
function render(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.drawImage(bg,0,0,W,H);drawCourt();if(g.state==='play'&&g.last===1&&g.bounces===0){let p=project(g.landing.x,g.landing.y);ctx.strokeStyle='#fff4bfa0';ctx.lineWidth=1.4;ctx.beginPath();ctx.ellipse(p.x,p.y,p.s*.35,p.s*.12,0,0,Math.PI*2);ctx.stroke();}
 if(g.canHit(0)){let rp=project(g.players[0].x,g.players[0].y);ctx.strokeStyle='#efffa6';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(rp.x,rp.y+3,rp.s*.68,rp.s*.2,0,0,Math.PI*2);ctx.stroke();}
 let objects=[{y:g.players[0].y,f:()=>drawPlayer(g.players[0],0)},{y:g.players[1].y,f:()=>drawPlayer(g.players[1],1)},{y:0,f:drawNet},{y:g.ball.y,f:drawBall}];objects.sort((a,b)=>a.y-b.y).forEach(o=>o.f());for(let q of particles){let p=project(q.x,q.y,q.z);ellipse(p.x,p.y,q.r*S,q.r*S*.45,'#efbf88',q.life*.5);}if(flash>0){ctx.fillStyle=`rgba(244,238,189,${flash*.04})`;ctx.fillRect(0,0,W,H);}
 // Soft dark corners keep foreground controls readable.
 let v=ctx.createLinearGradient(0,H*.76,0,H);v.addColorStop(0,'#18382800');v.addColorStop(1,'#193c345c');ctx.fillStyle=v;ctx.fillRect(0,H*.76,W,H*.24);
}
function beep(freq,duration,vol=.04){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),v=audio.createGain();o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+duration);v.gain.setValueAtTime(vol,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function toast(title,sub='',seconds=1.5){$('toast').classList.remove('hide');$('toast').querySelector('strong').textContent=title;$('toast').querySelector('span').textContent=sub;toastUntil=clock+seconds;}
function hud(){for(let i=0;i<2;i++){$('score'+i).textContent=g.score[i];$('server'+i).classList.toggle('hide',g.server!==i)}$('rally').textContent=g.rally>1?`RALLY ${g.rally}　·　最長回合 ${g.bestRally}`:g.state==='serve'?(g.server===0?'YOUR SERVE · 你的發球':'RETURN · 準備接發球'):'SUNSET COURT · 紅土球場';$('power').style.width=Math.min(100,g.charge/.78*100)+'%';$('hit').classList.toggle('charging',g.charging);$('powerlabel').textContent=g.queued>0?'準備揮拍…':g.charging?(g.charge>.6?'強力抽球':'蓄力中…'):'按住蓄力・放開擊球';$('hit').querySelector('strong').textContent=g.state==='serve'&&g.server===0?'發球':g.canHit(0)?'現在！':'擊球';$('hit').disabled=g.state==='serve'&&g.server===1||g.state==='point'||g.state==='fault';}
g.on(e=>{if(e.type==='hit'){beep(e.serve?220:310,.09,.055);flash=.35;}if(e.type==='bounce'){beep(115,.065,.02);for(let i=0;i<12;i++)particles.push({x:e.x+(Math.random()-.5)*.2,y:e.y+(Math.random()-.5)*.2,z:.03+Math.random()*.15,dx:(Math.random()-.5)*.65,dy:(Math.random()-.5)*.45,life:1,r:.01+Math.random()*.02});}if(e.type==='point'){toast(g.message,e.reason,1.7);beep(e.winner===0?660:160,.22);hud();}if(e.type==='serve'){toast(g.message,g.server===0?'按住擊球，放開發球':'準備接球',1.35);hud();}if(e.type==='fault')toast(g.message,g.reason,1.7);if(e.type==='match')setTimeout(showResult,650);});
function showPanel(id){$('veil').classList.remove('hide');for(let n of ['startPanel','pausePanel','resultPanel'])$(n).classList.toggle('hide',n!==id);}
function start(){let assist=$('assist').checked,difficulty=Number($('difficulty').value);g.reset();g.assist=assist;g.difficulty=difficulty;g.aim=aim=0;setAim(0);keys={};g.begin();$('veil').classList.add('hide');$('controls').classList.remove('hide');hud();}
function clearInput(){keys={};g.input={x:0,y:0};g.charging=false;g.queued=0;stickId=null;hitId=null;$('knob').style.transform='';}
function pause(){if(g.state==='ready'||g.state==='match')return;clearInput();g.paused=!g.paused;if(g.paused)showPanel('pausePanel');else $('veil').classList.add('hide');}
function showResult(){if(g.state!=='match')return;clearInput();$('toast').classList.add('hide');$('resultTitle').textContent=g.matchWinner===0?'紅土上的勝利':'再戰，下一場是你的';$('resultScore').textContent=`${g.score[0]} : ${g.score[1]}`;$('resultDetail').textContent=`最長回合 ${g.bestRally} 次擊球 · ${['休閒','標準','挑戰'][g.difficulty]}難度`;showPanel('resultPanel');}
$('start').onclick=start;$('again').onclick=start;$('restart').onclick=()=>{clearInput();g.state='ready';g.paused=false;showPanel('startPanel');$('controls').classList.add('hide');};$('pause').onclick=pause;$('resume').onclick=pause;$('sound').onclick=()=>{soundOn=!soundOn;$('sound').style.opacity=soundOn?'1':'.55';$('sound').setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');beep(420,.1);};$('sound').style.opacity='.55';
function setAim(value){aim=value;g.aim=aim;$('aimLeft').classList.toggle('active',aim<0);$('aimRight').classList.toggle('active',aim>0);$('aimLeft').setAttribute('aria-pressed',aim<0);$('aimRight').setAttribute('aria-pressed',aim>0);}
$('aimLeft').onclick=()=>setAim(aim<0?0:-.95);$('aimRight').onclick=()=>setAim(aim>0?0:.95);
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;keys[e.code]=true;if(e.code==='Space')g.press();if(e.code==='Escape')pause();if(e.code==='KeyJ')setAim(aim<0?0:-.95);if(e.code==='KeyL')setAim(aim>0?0:.95);});window.addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Space'){e.preventDefault();g.release();}});
let stickVector={x:0,y:0};function moveStick(e){let r=$('stick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),m=r.width*.31;if(l>m){dx*=m/l;dy*=m/l;}stickVector={x:dx/m,y:dy/m};$('knob').style.transform=`translate(${dx}px,${dy}px)`;}
$('stick').addEventListener('pointerdown',e=>{if(g.paused)return;e.preventDefault();stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);moveStick(e)});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickId)moveStick(e)});function endStick(e){if(e.pointerId===stickId){stickId=null;stickVector={x:0,y:0};$('knob').style.transform='';}}$('stick').addEventListener('pointerup',endStick);$('stick').addEventListener('pointercancel',endStick);$('stick').addEventListener('lostpointercapture',endStick);
$('hit').addEventListener('pointerdown',e=>{e.preventDefault();hitId=e.pointerId;hitStartX=e.clientX;$('hit').setPointerCapture(e.pointerId);g.press();});$('hit').addEventListener('pointermove',e=>{if(e.pointerId===hitId&&Math.abs(e.clientX-hitStartX)>14)setAim(clamp((e.clientX-hitStartX)/65,-.95,.95));});$('hit').addEventListener('pointerup',e=>{if(e.pointerId===hitId){hitId=null;g.release();}});$('hit').addEventListener('pointercancel',()=>{hitId=null;g.charging=false;});$('hit').addEventListener('lostpointercapture',()=>{if(hitId!==null){hitId=null;g.charging=false;}});
window.addEventListener('blur',()=>{if(!g.paused&&['play','serve','point','fault'].includes(g.state))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!g.paused&&['play','serve','point','fault'].includes(g.state))pause();});
function frame(ms){let dt=Math.min(.06,(ms-last)/1000||.016);last=ms;clock+=dt;acc+=dt;while(acc>=1/120){if(stickId===null)stickVector={x:0,y:0};g.input={x:clamp((keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0)+stickVector.x,-1,1),y:clamp((keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0)+stickVector.y,-1,1)};g.step(1/120);acc-=1/120;}particles=particles.filter(q=>q.life>0);for(let q of particles){q.x+=q.dx*dt;q.y+=q.dy*dt;q.life-=dt*2;}flash=Math.max(0,flash-dt*2);if(clock>toastUntil)$('toast').classList.add('hide');hud();render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
// Deliberately exposed read-only-friendly hooks for deterministic local QA.
window.clayClub={game:g,project,start,pause,render};
})();
